services:
  auth:
    build:
      context: .
      dockerfile: Dockerfile.ms-auth
    env_file: .env.docker
    environment:
      AUTH_TRANSPORT: tcp
      AUTH_HOST: 0.0.0.0
      AUTH_PORT: 4001
    networks: [icore]
    restart: unless-stopped

  upload:
    build:
      context: .
      dockerfile: Dockerfile.ms-upload
    env_file: .env.docker
    environment:
      UPLOAD_TRANSPORT: tcp
      UPLOAD_HOST: 0.0.0.0
      UPLOAD_PORT: 4002
    networks: [icore]
    restart: unless-stopped

  ai:
    build:
      context: .
      dockerfile: Dockerfile.ms-ai
    env_file: .env.docker
    environment:
      AI_TRANSPORT: tcp
      AI_HOST: 0.0.0.0
      AI_PORT: 4005
    networks: [icore]
    restart: unless-stopped

  gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    env_file: .env.docker
    environment:
      API_PORT: 3001
      AUTH_TRANSPORT: tcp
      AUTH_HOST: auth
      AUTH_PORT: 4001
      UPLOAD_TRANSPORT: tcp
      UPLOAD_HOST: upload
      UPLOAD_PORT: 4002
      AI_TRANSPORT: tcp
      AI_HOST: ai
      AI_PORT: 4005
    ports:
      - '3001:3001'
    depends_on:
      - auth
      - upload
      - ai
    networks: [icore]
    restart: unless-stopped

networks:
  icore:
    driver: bridge
