/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as DashboardStandardsRouteImport } from './routes/_dashboard/standards'
import { Route as DashboardProfileRouteImport } from './routes/_dashboard/profile'
import { Route as DashboardOrgRouteImport } from './routes/_dashboard/org'
import { Route as DashboardGapAnalysisRouteImport } from './routes/_dashboard/gap-analysis'
import { Route as DashboardFrameworksRouteImport } from './routes/_dashboard/frameworks'
import { Route as DashboardDashboardRouteImport } from './routes/_dashboard/dashboard'
import { Route as DashboardControlsRouteImport } from './routes/_dashboard/controls'
import { Route as AuthOauthCallbackRouteImport } from './routes/auth.oauth.callback'
import { Route as DashboardStandardsIdRouteImport } from './routes/_dashboard/standards.$id'
import { Route as DashboardAdminAiUsageRouteImport } from './routes/_dashboard/admin.ai-usage'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardStandardsRoute = DashboardStandardsRouteImport.update({
  id: '/standards',
  path: '/standards',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrgRoute = DashboardOrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGapAnalysisRoute = DashboardGapAnalysisRouteImport.update({
  id: '/gap-analysis',
  path: '/gap-analysis',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFrameworksRoute = DashboardFrameworksRouteImport.update({
  id: '/frameworks',
  path: '/frameworks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardControlsRoute = DashboardControlsRouteImport.update({
  id: '/controls',
  path: '/controls',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthOauthCallbackRoute = AuthOauthCallbackRouteImport.update({
  id: '/auth/oauth/callback',
  path: '/auth/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardStandardsIdRoute = DashboardStandardsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardStandardsRoute,
} as any)
const DashboardAdminAiUsageRoute = DashboardAdminAiUsageRouteImport.update({
  id: '/admin/ai-usage',
  path: '/admin/ai-usage',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/controls': typeof DashboardControlsRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/frameworks': typeof DashboardFrameworksRoute
  '/gap-analysis': typeof DashboardGapAnalysisRoute
  '/org': typeof DashboardOrgRoute
  '/profile': typeof DashboardProfileRoute
  '/standards': typeof DashboardStandardsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/ai-usage': typeof DashboardAdminAiUsageRoute
  '/standards/$id': typeof DashboardStandardsIdRoute
  '/auth/oauth/callback': typeof AuthOauthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/controls': typeof DashboardControlsRoute
  '/dashboard': typeof DashboardDashboardRoute
  '/frameworks': typeof DashboardFrameworksRoute
  '/gap-analysis': typeof DashboardGapAnalysisRoute
  '/org': typeof DashboardOrgRoute
  '/profile': typeof DashboardProfileRoute
  '/standards': typeof DashboardStandardsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/admin/ai-usage': typeof DashboardAdminAiUsageRoute
  '/standards/$id': typeof DashboardStandardsIdRoute
  '/auth/oauth/callback': typeof AuthOauthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/_dashboard/controls': typeof DashboardControlsRoute
  '/_dashboard/dashboard': typeof DashboardDashboardRoute
  '/_dashboard/frameworks': typeof DashboardFrameworksRoute
  '/_dashboard/gap-analysis': typeof DashboardGapAnalysisRoute
  '/_dashboard/org': typeof DashboardOrgRoute
  '/_dashboard/profile': typeof DashboardProfileRoute
  '/_dashboard/standards': typeof DashboardStandardsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/_dashboard/admin/ai-usage': typeof DashboardAdminAiUsageRoute
  '/_dashboard/standards/$id': typeof DashboardStandardsIdRoute
  '/auth/oauth/callback': typeof AuthOauthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/controls'
    | '/dashboard'
    | '/frameworks'
    | '/gap-analysis'
    | '/org'
    | '/profile'
    | '/standards'
    | '/auth/callback'
    | '/admin/ai-usage'
    | '/standards/$id'
    | '/auth/oauth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/controls'
    | '/dashboard'
    | '/frameworks'
    | '/gap-analysis'
    | '/org'
    | '/profile'
    | '/standards'
    | '/auth/callback'
    | '/admin/ai-usage'
    | '/standards/$id'
    | '/auth/oauth/callback'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/login'
    | '/_dashboard/controls'
    | '/_dashboard/dashboard'
    | '/_dashboard/frameworks'
    | '/_dashboard/gap-analysis'
    | '/_dashboard/org'
    | '/_dashboard/profile'
    | '/_dashboard/standards'
    | '/auth/callback'
    | '/_dashboard/admin/ai-usage'
    | '/_dashboard/standards/$id'
    | '/auth/oauth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthOauthCallbackRoute: typeof AuthOauthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/standards': {
      id: '/_dashboard/standards'
      path: '/standards'
      fullPath: '/standards'
      preLoaderRoute: typeof DashboardStandardsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/profile': {
      id: '/_dashboard/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/org': {
      id: '/_dashboard/org'
      path: '/org'
      fullPath: '/org'
      preLoaderRoute: typeof DashboardOrgRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/gap-analysis': {
      id: '/_dashboard/gap-analysis'
      path: '/gap-analysis'
      fullPath: '/gap-analysis'
      preLoaderRoute: typeof DashboardGapAnalysisRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/frameworks': {
      id: '/_dashboard/frameworks'
      path: '/frameworks'
      fullPath: '/frameworks'
      preLoaderRoute: typeof DashboardFrameworksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard': {
      id: '/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/controls': {
      id: '/_dashboard/controls'
      path: '/controls'
      fullPath: '/controls'
      preLoaderRoute: typeof DashboardControlsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/oauth/callback': {
      id: '/auth/oauth/callback'
      path: '/auth/oauth/callback'
      fullPath: '/auth/oauth/callback'
      preLoaderRoute: typeof AuthOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/standards/$id': {
      id: '/_dashboard/standards/$id'
      path: '/$id'
      fullPath: '/standards/$id'
      preLoaderRoute: typeof DashboardStandardsIdRouteImport
      parentRoute: typeof DashboardStandardsRoute
    }
    '/_dashboard/admin/ai-usage': {
      id: '/_dashboard/admin/ai-usage'
      path: '/admin/ai-usage'
      fullPath: '/admin/ai-usage'
      preLoaderRoute: typeof DashboardAdminAiUsageRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardStandardsRouteChildren {
  DashboardStandardsIdRoute: typeof DashboardStandardsIdRoute
}

const DashboardStandardsRouteChildren: DashboardStandardsRouteChildren = {
  DashboardStandardsIdRoute: DashboardStandardsIdRoute,
}

const DashboardStandardsRouteWithChildren =
  DashboardStandardsRoute._addFileChildren(DashboardStandardsRouteChildren)

interface DashboardRouteChildren {
  DashboardControlsRoute: typeof DashboardControlsRoute
  DashboardDashboardRoute: typeof DashboardDashboardRoute
  DashboardFrameworksRoute: typeof DashboardFrameworksRoute
  DashboardGapAnalysisRoute: typeof DashboardGapAnalysisRoute
  DashboardOrgRoute: typeof DashboardOrgRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardStandardsRoute: typeof DashboardStandardsRouteWithChildren
  DashboardAdminAiUsageRoute: typeof DashboardAdminAiUsageRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardControlsRoute: DashboardControlsRoute,
  DashboardDashboardRoute: DashboardDashboardRoute,
  DashboardFrameworksRoute: DashboardFrameworksRoute,
  DashboardGapAnalysisRoute: DashboardGapAnalysisRoute,
  DashboardOrgRoute: DashboardOrgRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardStandardsRoute: DashboardStandardsRouteWithChildren,
  DashboardAdminAiUsageRoute: DashboardAdminAiUsageRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthOauthCallbackRoute: AuthOauthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
