import { Document, Page, Text, View, StyleSheet, pdf } from '@react-pdf/renderer';
import type { ReportTemplate } from '@icore/shared';
import type { GapAnalysis } from '@/queries/gap';
import type { StandardsDocument } from '@/queries/notes';
import { downloadBlob, dateStamp } from './download';

const PRODUCT = 'ComplianceIQ';

const styles = StyleSheet.create({
  page: { paddingTop: 48, paddingBottom: 56, paddingHorizontal: 44, fontSize: 9, color: '#1f2937' },
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    borderBottomWidth: 2,
    paddingBottom: 10,
    marginBottom: 18,
  },
  brand: { fontSize: 16, fontWeight: 'bold' },
  reportType: { fontSize: 10, marginTop: 2, color: '#6b7280' },
  metaRight: { textAlign: 'right', fontSize: 8, color: '#6b7280' },
  sectionTitle: {
    fontSize: 11,
    fontWeight: 'bold',
    marginBottom: 6,
    marginTop: 14,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  summary: { fontSize: 9.5, lineHeight: 1.5, color: '#374151' },
  scoreRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 8 },
  scoreNum: { fontSize: 30, fontWeight: 'bold' },
  scoreLabel: { fontSize: 8, color: '#6b7280', textTransform: 'uppercase', letterSpacing: 0.5 },
  badge: {
    fontSize: 7.5,
    fontWeight: 'bold',
    paddingVertical: 2,
    paddingHorizontal: 5,
    borderRadius: 3,
    color: '#ffffff',
  },
  // Tables
  tHead: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderColor: '#d1d5db',
    paddingBottom: 4,
    marginBottom: 2,
  },
  tRow: {
    flexDirection: 'row',
    borderBottomWidth: 0.5,
    borderColor: '#e5e7eb',
    paddingVertical: 4,
  },
  th: { fontSize: 8, fontWeight: 'bold', color: '#6b7280', textTransform: 'uppercase' },
  td: { fontSize: 8.5, color: '#374151' },
  footer: {
    position: 'absolute',
    bottom: 24,
    left: 44,
    right: 44,
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderTopWidth: 0.5,
    borderColor: '#d1d5db',
    paddingTop: 6,
    fontSize: 7,
    color: '#9ca3af',
  },
});

const SEVERITY_BG: Record<string, string> = {
  critical: '#dc2626',
  high: '#d97706',
  medium: '#2563eb',
  low: '#6b7280',
};

function riskLevel(score: number): string {
  return score >= 70 ? 'HIGH' : score >= 40 ? 'MEDIUM' : 'LOW';
}

function Header({
  template,
  reportType,
  orgName,
  date,
}: {
  template: ReportTemplate;
  reportType: string;
  orgName: string;
  date: string;
}) {
  const accent = template.accentColor || '#16a34a';
  const brand = template.brandName || orgName || PRODUCT;
  return (
    <View style={[styles.headerRow, { borderBottomColor: accent }]}>
      <View>
        <Text style={[styles.brand, { color: accent }]}>{brand}</Text>
        <Text style={styles.reportType}>{reportType}</Text>
      </View>
      <View style={styles.metaRight}>
        <Text>Date: {date}</Text>
        {orgName ? <Text>Organization: {orgName}</Text> : null}
        <Text>Template: {template.name}</Text>
      </View>
    </View>
  );
}

function Footer({ template }: { template: ReportTemplate }) {
  return (
    <View style={styles.footer} fixed>
      <Text>
        {template.footerNote ? `${template.footerNote} · ` : ''}Generated by {PRODUCT}
      </Text>
      <Text render={({ pageNumber, totalPages }) => `Page ${pageNumber} / ${totalPages}`} />
    </View>
  );
}

function GapDoc({
  gap,
  template,
  orgName,
}: {
  gap: GapAnalysis;
  template: ReportTemplate;
  orgName: string;
}) {
  const r = gap.result;
  const accent = template.accentColor || '#16a34a';
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Header
          template={template}
          reportType="Gap Analysis Report"
          orgName={orgName}
          date={new Date(gap.createdAt).toLocaleString()}
        />

        <View style={styles.scoreRow}>
          <Text style={[styles.scoreNum, { color: accent }]}>{r.riskScore}</Text>
          <View>
            <Text style={styles.scoreLabel}>Risk Score / 100</Text>
            <Text style={[styles.badge, { backgroundColor: accent, marginTop: 2 }]}>
              {riskLevel(r.riskScore)}
            </Text>
          </View>
        </View>

        {template.includeSummary && (
          <View>
            <Text style={styles.sectionTitle}>Summary</Text>
            <Text style={styles.summary}>{r.summary}</Text>
          </View>
        )}

        {template.includeDetails && (
          <View>
            <Text style={styles.sectionTitle}>Critical Gaps</Text>
            {r.criticalGaps.length === 0 ? (
              <Text style={styles.summary}>No critical gaps identified.</Text>
            ) : (
              <View>
                <View style={styles.tHead}>
                  <Text style={[styles.th, { width: '18%' }]}>Control</Text>
                  <Text style={[styles.th, { width: '17%' }]}>Severity</Text>
                  <Text style={[styles.th, { width: '65%' }]}>Description</Text>
                </View>
                {r.criticalGaps.map((g, i) => (
                  <View style={styles.tRow} key={i} wrap={false}>
                    <Text style={[styles.td, { width: '18%' }]}>{g.controlId}</Text>
                    <View style={{ width: '17%' }}>
                      <Text
                        style={[
                          styles.badge,
                          {
                            backgroundColor: SEVERITY_BG[g.severity] ?? '#6b7280',
                            alignSelf: 'flex-start',
                          },
                        ]}
                      >
                        {g.severity.toUpperCase()}
                      </Text>
                    </View>
                    <Text style={[styles.td, { width: '65%' }]}>{g.description}</Text>
                  </View>
                ))}
              </View>
            )}
          </View>
        )}

        {template.includeRecommendations && (
          <View>
            <Text style={styles.sectionTitle}>Recommendations</Text>
            <View style={styles.tHead}>
              <Text style={[styles.th, { width: '10%' }]}>#</Text>
              <Text style={[styles.th, { width: '74%' }]}>Action</Text>
              <Text style={[styles.th, { width: '16%' }]}>Effort</Text>
            </View>
            {r.recommendations.map((rec, i) => (
              <View style={styles.tRow} key={i} wrap={false}>
                <Text style={[styles.td, { width: '10%' }]}>{rec.priority}</Text>
                <Text style={[styles.td, { width: '74%' }]}>{rec.action}</Text>
                <Text style={[styles.td, { width: '16%' }]}>{rec.effort}</Text>
              </View>
            ))}
          </View>
        )}

        <Footer template={template} />
      </Page>
    </Document>
  );
}

function StandardsDoc({
  doc,
  frameworks,
  template,
  orgName,
}: {
  doc: StandardsDocument;
  frameworks: { id: string; name: string }[];
  template: ReportTemplate;
  orgName: string;
}) {
  const fwName = (id: string) => frameworks.find((f) => f.id === id)?.name ?? id;
  const fwList = doc.frameworkIds.map(fwName).join(', ');
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Header
          template={template}
          reportType="Standards Document"
          orgName={orgName}
          date={new Date(doc.createdAt).toLocaleString()}
        />

        {template.includeSummary && (
          <View>
            <Text style={styles.sectionTitle}>Frameworks</Text>
            <Text style={styles.summary}>{fwList}</Text>
            <Text style={[styles.summary, { marginTop: 4 }]}>
              {doc.standards.length} standard(s) · status: {doc.status} · workflow:{' '}
              {doc.workflowStatus}
            </Text>
          </View>
        )}

        {template.includeDetails && (
          <View>
            <Text style={styles.sectionTitle}>Standards</Text>
            <View style={styles.tHead}>
              <Text style={[styles.th, { width: '13%' }]}>Code</Text>
              <Text style={[styles.th, { width: '22%' }]}>Title</Text>
              <Text style={[styles.th, { width: '20%' }]}>Objective</Text>
              <Text style={[styles.th, { width: '15%' }]}>Scope</Text>
              <Text style={[styles.th, { width: '30%' }]}>Requirements</Text>
            </View>
            {doc.standards.map((std, i) => (
              <View style={styles.tRow} key={i} wrap={false}>
                <Text style={[styles.td, { width: '13%' }]}>{std.code}</Text>
                <Text style={[styles.td, { width: '22%' }]}>{std.title}</Text>
                <Text style={[styles.td, { width: '20%' }]}>{std.objective}</Text>
                <Text style={[styles.td, { width: '15%' }]}>{std.scope}</Text>
                <Text style={[styles.td, { width: '30%' }]}>{std.requirements.join('; ')}</Text>
              </View>
            ))}
          </View>
        )}

        <Footer template={template} />
      </Page>
    </Document>
  );
}

export async function exportGapPdf(
  gap: GapAnalysis,
  template: ReportTemplate,
  orgName: string,
): Promise<void> {
  const blob = await pdf(<GapDoc gap={gap} template={template} orgName={orgName} />).toBlob();
  downloadBlob(blob, `gap-analysis-${dateStamp(gap.createdAt)}.pdf`);
}

export async function exportStandardsPdf(
  doc: StandardsDocument,
  frameworks: { id: string; name: string }[],
  template: ReportTemplate,
  orgName: string,
): Promise<void> {
  const blob = await pdf(
    <StandardsDoc doc={doc} frameworks={frameworks} template={template} orgName={orgName} />,
  ).toBlob();
  downloadBlob(blob, `standards-${dateStamp(doc.createdAt)}.pdf`);
}
