import type {
  AiStrategy,
  ChatContext,
  ChatMessage,
  ChatResult,
  ControlFinding,
  GapAnalysisResult,
  GeneratedControl,
  OrgProfile,
  StandardsResult,
} from '../ai';

export class FakeAiStrategy implements AiStrategy {
  async chat(messages: ChatMessage[], _context: ChatContext): Promise<ChatResult> {
    const echo = messages.map((m) => `[${m.role}] ${m.content}`).join(' | ');
    return { text: `FAKE: ${echo}`, inputTokens: messages.length * 10, outputTokens: 20 };
  }

  async generateStandards(
    _orgProfile: OrgProfile,
    frameworkIds: string[],
  ): Promise<StandardsResult[]> {
    return frameworkIds.map((frameworkId) => ({
      frameworkId,
      controls: [
        {
          id: `${frameworkId}-FAKE-001`,
          title: 'Fake Control',
          description: 'Generated by FakeAiStrategy for testing.',
          implementationGuidance: 'No-op — replace with real strategy in production.',
        },
      ],
    }));
  }

  async analyzeGap(
    _controls: GeneratedControl[],
    _findings: ControlFinding[],
  ): Promise<GapAnalysisResult> {
    return {
      summary: 'Fake gap analysis — no real assessment performed.',
      criticalGaps: [],
      recommendations: [],
      riskScore: 0,
    };
  }
}
