import type {
  AiStrategy,
  ChatContext,
  ChatMessage,
  ChatResult,
  ControlFinding,
  GapAnalysisResult,
  GeneratedStandard,
  OrgProfile,
  StandardsResult,
} from '../ai';

export class FakeAiStrategy implements AiStrategy {
  async chat(messages: ChatMessage[], _context: ChatContext): Promise<ChatResult> {
    const echo = messages.map((m) => `[${m.role}] ${m.content}`).join(' | ');
    return { text: `FAKE: ${echo}`, inputTokens: messages.length * 10, outputTokens: 20 };
  }

  async generateStandards(
    _orgProfile: OrgProfile,
    frameworkIds: string[],
  ): Promise<StandardsResult[]> {
    return frameworkIds.map((frameworkId) => ({
      frameworkId,
      standards: [
        {
          id: `${frameworkId}-FAKE-STD-001`,
          title: 'Fake Standard',
          objective: 'Generated by FakeAiStrategy for testing.',
          scope: 'All systems.',
          requirements: ['Requirement 1 — no-op placeholder.'],
        },
      ],
    }));
  }

  async analyzeGap(
    _standards: GeneratedStandard[],
    _findings: ControlFinding[],
  ): Promise<GapAnalysisResult> {
    return {
      summary: 'Fake gap analysis — no real assessment performed.',
      criticalGaps: [],
      recommendations: [],
      riskScore: 0,
    };
  }
}
